return {
  title = "Biome",
  author = "stolmine",
  name = "biome",
  keyword = "utility, effect, oscillator, filter",
  units = {
    { title = "NR",                moduleName = "NR",                    category = "Biome", keywords = "rhythm, gate, sequencer, trigger" },
    { title = "94 Discont",        moduleName = "Discont",               category = "Biome", keywords = "waveshaper, saturation, distortion, effect" },
    { title = "Latch Filter",      moduleName = "LatchFilter",           category = "Biome", keywords = "filter, latch, digital, effect" },
    { title = "Gesture",           moduleName = "GestureSeq",            category = "Biome", keywords = "sequencer, gesture, recorder, looper, CV" },
    { title = "Gated Slew",       moduleName = "GatedSlewLimiter",      category = "Biome", keywords = "slew, gate, utility, filter, envelope" },
    { title = "Tilt EQ",          moduleName = "TiltEQ",                category = "Biome", keywords = "eq, tilt, tone, filter, effect" },
    { title = "DJ Filter",        moduleName = "DJFilter",              category = "Biome", keywords = "filter, dj, lp, hp, sweep, effect" },
    { title = "Gridlock",         moduleName = "Gridlock",              category = "Biome", keywords = "gate, priority, router, cv, utility" },
    { title = "Integrator",       moduleName = "Integrator",            category = "Biome", keywords = "integrator, accumulator, cv, utility, modulation" },
    { title = "Spectral Follower", moduleName = "SpectralFollower",     category = "Biome", keywords = "envelope, follower, bandpass, spectral, detector, cv" },
    { title = "Quantoffset",      moduleName = "Quantoffset",           category = "Biome", keywords = "quantizer, offset, cv, utility, pitch" },
    { title = "PSR",              moduleName = "PingableScaledRandom",  category = "Biome", keywords = "random, trigger, cv, utility, modulation, sample and hold, psr" },
    { title = "Bletchley Park",   moduleName = "CodescanOsc",           category = "Biome", keywords = "oscillator, wavetable, codescan, generator, digital, bletchley" },
    { title = "Station X",        moduleName = "CodescanFilter",        category = "Biome", keywords = "filter, fir, convolution, codescan, effect, digital, station x" },
    { title = "Fade Mixer",       moduleName = "FadeMixer",             category = "Biome", keywords = "mixer, crossfade, fade, utility, mute, solo" },
    { title = "Fade Mixer 6",     moduleName = "FadeMixer6",            category = "Biome", keywords = "mixer, crossfade, fade, utility, mute, solo, 6" },
    { title = "Fade Mixer 8",     moduleName = "FadeMixer8",            category = "Biome", keywords = "mixer, crossfade, fade, utility, mute, solo, 8" },
    { title = "Varishape Voice", moduleName = "VarishapeVoice",       category = "Biome", keywords = "oscillator, voice, synth, varishape, generator" },
    { title = "Varishape Osc",  moduleName = "VarishapeOsc",        category = "Biome", keywords = "oscillator, varishape, polyblep, generator" },
    { title = "Transport",     moduleName = "Transport",            category = "Biome", keywords = "clock, transport, gate, trigger, utility" },
    { title = "Constant Random", moduleName = "ConstantRandom",  category = "Biome", keywords = "random, noise, cv, utility, modulation, sample and hold, lfo" },
    { title = "Expo D",       moduleName = "ExpoD",                category = "Biome", keywords = "envelope, decay, exponential, trigger, eg, percussion, modulation" },
    { title = "Expo AD",      moduleName = "ExpoAD",               category = "Biome", keywords = "envelope, attack, decay, exponential, trigger, eg, modulation" },
    { title = "Mordant",      moduleName = "Mordant",              category = "Biome", keywords = "voice, bass, acid, synth, oscillator, filter, resonant, mono, generator" },
    { title = "Spectral Freeze", moduleName = "SpectralFreeze",    category = "Biome", keywords = "freeze, spectral, fft, phase vocoder, texture, sustain, drone, effect, ice, kryos" }
  }
}
